//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "osv")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cve: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub purl: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
